sudo: required
language: cpp
dist: trusty
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
       brew install cartr/qt4/qt 
       ;
    fi
  - sudo -H pip install nose numpy
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - PYTHONPATH="."
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=RelwithDebInfo .. && make -j4 && make install
  - cd .. && nosetests --exe
